apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebdeployment
  labels:
    app: myrepo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myrepo
  template:
    metadata:
      labels:
        app: myrepo
    spec:
      containers:
      - name: myrepo
        image: nginx
        ports:
        - containerPort: 8080
